//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ASMLight.Properties.Resources.get_ResourceManager():System.Resources.ResourceMana" +
    "ger")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ASMLight.Properties.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ASMLight.Properties.Resources.set_Culture(System.Globalization.CultureInfo):Void")]

namespace ASMLight.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASMLight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrowleft_green_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("arrowleft_green_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap arrowright_green_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("arrowright_green_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap copy_clipboard_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("copy_clipboard_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap cut_clipboard_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("cut_clipboard_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap new_document_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("new_document_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap open_document_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("open_document_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap paste_clipboard_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("paste_clipboard_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap properties_doc_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("properties_doc_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap redo_square_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("redo_square_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap save_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("save_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap save_green_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("save_green_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap stop_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("stop_16", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap undo_square_16 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("undo_square_16", resourceCulture)));
            }
        }
    }
}
